language: python
sudo: required
dist: xenial

matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
- pip install tox coveralls

script:
  tox

before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
